name: Doctochat Dev CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm install

      #     MD
      - name: Create env configs
        run: |
          echo "${{ secrets.ENV_FILE_DEV }}" > .env
          echo "${{ secrets.REGION_MD }}" >> .env
          echo "${{ secrets.API_PATH_MD }}" >> .env
          echo "${{ secrets.GOOGLE_RECAPTCHA_SITE_KEY }}" >> .env
      - name: Build
        run: CI=false npm run build
      - name: SSH Server Deploy MD
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SSH_PASS }}
          private_key: ${{ secrets.SERVER_PRIVATE_KEY }}
          scp_source: "out/"
          scp_target: ${{ secrets.TARGET_APP_MD_DEV }}
      - name: Send notification to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Deployed MD
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
      #     RO
      - name: Create env configs RO
        run: |
          echo "${{ secrets.ENV_FILE_DEV }}" > .env
          echo "${{ secrets.REGION_RO }}" >> .env
          echo "${{ secrets.API_PATH_RO }}" >> .env
          echo "${{ secrets.GOOGLE_RECAPTCHA_SITE_KEY }}" >> .env
      - name: Build RO
        run: CI=false npm run build
      - name: SSH Server Deploy RO
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SSH_PASS }}
          private_key: ${{ secrets.SERVER_PRIVATE_KEY }}
          scp_source: "out/"
          scp_target: ${{ secrets.TARGET_APP_RO_DEV }}
      - name: Send notification to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Deployed RO
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
      #     ONLINE
      - name: Create env configs ONLINE
        run: |
          echo "${{ secrets.ENV_FILE_DEV }}" > .env
          echo "${{ secrets.REGION_RO }}" >> .env
          echo "${{ secrets.API_PATH_ONLINE }}" >> .env
          echo "${{ secrets.GOOGLE_RECAPTCHA_SITE_KEY }}" >> .env
      - name: Build ONLINE
        run: CI=false npm run build
      - name: SSH Server Deploy ONLINE
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SSH_PASS }}
          private_key: ${{ secrets.SERVER_PRIVATE_KEY }}
          scp_source: "out/"
          scp_target: ${{ secrets.TARGET_APP_ONLINE_DEV }}
          
      - name: Send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          format: html
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ <b>[DEV] Doctorchat Clients APP</b>
            🥷 <b>User</b>: ${{ github.actor }}
            📂 <b>Commit:</b> <a href="https://github.com/${{ github.repository }}/commit/${{github.sha}}">${{ github.event.commits[0].message }}</a>
            📌 <b>Branch:</b> ${{ github.ref }}
            📌 <b>Commit:</b> ${{ github.sha }}
            📌 <b>Repository:</b> ${{ github.repository }}
            📌 <b>Workflow:</b> ${{ github.workflow }}
            📌 <b>Run:</b> ${{ github.run_id }}
            📌 <b>Run Number:</b> ${{ github.run_number }}
