name: Doctorchat DEV CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm install

      - name: Create env configs
        run: |
          echo "${{ secrets.DEV_ENV }}" > .env
      - name: Build
        run: CI=false npm run build
      - name: SSH Server Deploy DEV
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: '31.172.77.196'
          username: 'doctorchat-app-dev'
          password: ${{ secrets.APP_PASSWORD }}
          scp_source: "out"
          scp_target: "/home/doctorchat-app-dev/htdocs/app-dev.doctorchat.md/"
